version: '3.3'

services:
  nginx:
    image: nginx:1.27.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/mydata/certbot/conf:/etc/letsencrypt
      - /tmp/mydata/certbot/www:/var/www/certbot
    depends_on:
      - myapp
    networks:
      - my-app-net

  myapp:
    image: IMAGE_TAG
    container_name: myapp
    ports:
      - "8080:8080"
    networks:
      - my-app-net

  certbot:
    image: certbot/certbot:v3.1.0
    container_name: certbot
    volumes:
      - /tmp/mydata/certbot/conf:/etc/letsencrypt
      - /tmp/mydata/certbot/www:/var/www/certbot
    networks:
      - my-app-net

networks:
  my-app-net:
    driver: bridge
